name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - pub

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Adjust this to your Node.js version

    - name: Install server dependencies
      run: npm ci

    - name: Install client dependencies
      run: cd client && npm ci

    - name: Build application
      run: npm run build

    - name: Create deployment package
      run: |
        mkdir deploy
        cp package.json deploy/
        cp -r dist deploy/
        cp Procfile deploy/
        cd deploy && zip -r ../deploy.zip .

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ secrets.EB_APPLICATION_NAME }}
        environment_name: ${{ secrets.EB_ENVIRONMENT_NAME }}
        version_label: ${{ github.sha }}
        region: ${{ secrets.AWS_REGION }}
        deployment_package: deploy.zip